Repository QEDK/volunteery, pull requests merged in 2020-12, with the labels that each got.

#13 docs: Add information to README
  README.md
Labels: documentation

#19 Add the swipecard and floating action button
  .idea/libraries/Dart_Packages.xml
  social_good/assets/fonts/CrimsonText-Regular.ttf
  social_good/assets/images/beach.jpg
  social_good/assets/images/blood.jpg
  social_good/assets/images/girl.jpeg
  social_good/assets/images/senior.jpg
  social_good/assets/images/tree.jpg
  social_good/lib/globals/myDimens.dart
  social_good/lib/globals/myString.dart
  social_good/lib/main.dart
  social_good/lib/pages/volunteer/eventDesciption.dart
  social_good/lib/pages/volunteer/volunteerForm.dart
  social_good/lib/pages/volunteer/volunteerHomeScreen.dart
  social_good/lib/widgets/fabCircular.dart
  social_good/pubspec.yaml
Labels: enhancement

#29 :tada: feat: write unit and widget tests for CI/CD
  .idea/codeStyles/Project.xml
  .idea/libraries/Dart_Packages.xml
  social_good/lib/pages/volunteer/interestedEvents.dart
  social_good/lib/pages/volunteer/volunteerForm.dart
  social_good/lib/widgets/buildAdressTest.dart
  social_good/lib/widgets/fabCircular.dart
  social_good/test/buildAdressTest_widget_test.dart
  social_good/test/dateTime_unit_test.dart
Labels: enhancement

#31 general: Add runner for Flutter tests
  .github/workflows/test.yaml
  social_good/test/dateTime_unit_test.dart
Labels: general

#32 general: Dockerize releases and deploy to GitHub
  .github/workflows/docker.yaml
  Dockerfile
Labels: general
